# Generated by Django 4.1.2 on 2022-10-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_surveyquestion_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyuseranswer',
            name='submited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
