# Generated by Django 4.1.2 on 2022-10-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveyuseranswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyquestionalternative',
            options={},
        ),
        migrations.RemoveField(
            model_name='surveyquestionalternative',
            name='order',
        ),
    ]
