# Generated by Django 4.1.2 on 2022-10-07 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_surveyquestionalternative_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyuseranswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='survey.surveyquestion'),
            preserve_default=False,
        ),
    ]
