# Generated by Django 4.1.2 on 2022-10-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_surveyuseranswer_submited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
