# Generated by Django 4.1.2 on 2022-10-10 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_survey_user_alter_survey_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestionalternative',
            name='survey_choice_alternative',
            field=models.CharField(choices=[('A', 'Alternativa A'), ('B', 'Alternativa B'), ('C', 'Alternativa C'), ('D', 'Alternativa D'), ('E', 'Alternativa E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='surveyuseranswer',
            name='user_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveyquestionalternative'),
        ),
    ]
