# Generated by Django 4.1.2 on 2022-10-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_alter_surveyquestionalternative_survey_choice_alternative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyuseranswer',
            name='user_answer',
            field=models.TextField(choices=[('A', 'Alternativa A'), ('B', 'Alternativa B'), ('C', 'Alternativa C'), ('D', 'Alternativa D'), ('E', 'Alternativa E')], max_length=1),
        ),
    ]
